name: Run Python Docker Action

on: [push, pull_request]

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Exécuter l'action Docker
        uses: ./
        with:
          root_domain: "web-id.fr"
